# https://github.com/behaviorbot/welcome

newIssueWelcomeComment: >
  The supervisor is busy on a call, come back soon
  
  ['supervisor'](./apps/welcome/new_issue
png) 


newPRWelcomeComment: >
  Thanks for opening this pull B


firstPRMergeComment: >
  Congrats on merging your firsB
