language: python
python:
  - "3.6"
notifications:
  email: false
cache: pip
install:
  - pip install argparse
  - python setup.py install
  - python3 -m pip install coverage
script:
  - python3 -m coverage run ./cushead.py -file ./test/cushead.txt
  - codecov --token=6c5354d8-7b78-4212-88a1-bf0df669e075