language: python
python:
  - "3.8"
notifications:
  email: false
cache: pip
install:
  - pip install codecov
  - python3 -m pip install coverage
  - pip install -r requirements.txt
script:
  # success
  - python3 -m coverage run cushead.py -default test/test.json --images
  - python3 -m coverage run cushead.py -config test/test.json
  # bad
  - python3 -m coverage run cushead.py
  - python3 -m coverage run cushead.py -default
  - python3 -m coverage run cushead.py -config
  - python3 -m coverage run cushead.py -config test/test.json --images
  - python3 -m coverage run cushead.py .
  - codecov