language: python
python:
  - "3.8"
notifications:
  email: false
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  # success
  - python3 -m coverage run -a cushead.py -default test/test.json --images
  - python3 -m coverage run -a cushead.py -config test/test.json
  - python3 -m coverage run -a cushead.py -h
  # bad
  - python3 -m coverage run -a cushead.py
  - python3 -m coverage run -a cushead.py .
  - python3 -m coverage run -a cushead.py -default
  - python3 -m coverage run -a cushead.py -config
  - python3 -m coverage run -a cushead.py -config . --images
  - python3 -m coverage run -a cushead.py -config .
  - codecov