language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
notifications:
  email: false
cache: pip
install:
  - pip install codecov
  - python3 -m pip install coverage
  - pip install -r requirements.txt
script:
  - python3 -m converage run cushead.py -default testing/test.json --images
  - python3 -m coverage run cushead.py -config testing/test.json
  - codecov