language: python
python:
  - "3.6"
notifications:
  email: false
cache: pip
install:
  - pip install argparse
  - pip install codecov
  - python setup.py install
  - python3 -m pip install coverage
script:
  - python3 -m coverage run ./test/test.py
  - codecov