language: python
python:
  - "3.8"
notifications:
  email: false
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  # Test correct usage
  - python3 -m coverage run -a cushead.py -default test/test.json --images
  - python3 -m coverage run -a cushead.py -config test/test.json
  - python3 -m coverage run -a cushead.py -h
  # Test bad usage
  - assertError=0
  - python3 -m coverage run -a cushead.py || let "assertError+=1"
  - python3 -m coverage run -a cushead.py . || let "assertError+=1"
  - python3 -m coverage run -a cushead.py -default || let "assertError+=1"
  - python3 -m coverage run -a cushead.py -config || let "assertError+=1"
  - python3 -m coverage run -a cushead.py -config . --images || let "assertError+=1"
  - python3 -m coverage run -a cushead.py -config . || let "assertError+=1"
  - if [[ "assertError" -eq 6 ]]; then echo "All errors pass tests"; else echo $assertError; fi
  - codecov