language: python
python:
  - '3.8'
notifications:
  email: false
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - python -m coverage run -a test/test_exceptions.py
  - codecov -X gcov
