language: python
python:
  - '3.8'
notifications:
  email: false
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - python -m coverage run -a tests/test_exceptions.py
  - python -m coverage run -a tests/test_configs.py
  - python -m coverage run -a tests/test_packages.py
  - python -m coverage run -a tests/test_setup.py
  - codecov -X gcov
