language: python
python:
  - "3.8"
notifications:
  email: false
cache: pip
install:
  - pip install codecov
  - python3 -m pip install coverage
  - pip install -r requirements.txt
script:
  # success
  - python3 -m coverage run cushead.py -default test/test.json --images
  - python3 -m coverage run cushead.py -config test/test.json
  # bad
  - python3 -m coverage run cushead.py || echo "assert exit 1" || echo exit 1
  - python3 -m coverage run cushead.py -default || echo "assert exit 1" || echo exit 1
  - python3 -m coverage run cushead.py -config || echo "assert exit 1" || echo exit 1
  - python3 -m coverage run cushead.py -config test/test.json --images || echo "assert exit 1" || echo exit 1
  - python3 -m coverage run cushead.py . || echo "assert exit 1" || echo exit 1
  - codecov