language: python
python:
  - "3.6"
  - "3.7"
notifications:
  email: false
cache: pip
install:
  - pip install codecov
  - python3 -m pip install coverage
script:
  - python3 -m coverage run .cushead.py -config testing/set.json
  - codecov