language: python
python:
  - "3.8"
notifications:
  email: false
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  # Test correct usage
  - python3 -m coverage run -a cushead.py -default test/test.json --images
  - python3 -m coverage run -a cushead.py -config test/test.json
  - python3 -m coverage run -a cushead.py -h
  # Test bad usage
  - assertError=0; errorAmounts=0
  - function testErrors() { $* || let "assertError+=1"; let "testsAmount+=1" }
  - testErrors python3 -m coverage run -a cushead.py
  - testErrors python3 -m coverage run -a cushead.py .
  - testErrors python3 -m coverage run -a cushead.py -default
  - testErrors python3 -m coverage run -a cushead.py -config
  - testErrors python3 -m coverage run -a cushead.py -config .
  - testErrors python3 -m coverage run -a cushead.py -config test/test.json --images
  - if [[ "assertError" -eq "testsAmount" ]]; then echo "All errors pass tests"; else echo $assertError; fi
  - codecov