# Configuration for welcome - https://github.com/behaviorbot/welcome

newIssueWelcomeComment: >
  Thanks for opening your first issue here!
  
newPRWelcomeComment: >
  Thanks for opening this pull request!
  
firstPRMergeComment: >
  Congrats on merging your first pull request! We are proud of you!
