name: Lighthouse CI

on: [pull_request]

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install and run Lighthouse CI
        run: npm i -g @lhci/cli
      - name: Run Lighthouse CI
        run: |
          lhci --config docs/examples/crossorigin_static_url/.lighthouserc.js autorun
          lhci --config docs/examples/relative_static_url/.lighthouserc.js autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
