name: Lighthouse

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install lhci
        run: npm i -g @lhci/cli
      - name: Run lhci
        run: lhci --config docs/example/.lighthouserc.js autorun
