name: Python Observant

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  Python-Observant:
    name: Python Observant
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Python Observant
        uses: lucasvazq/auto-linter@master
        with:
          requirements: "pip install -r requirements.txt"
          max_line_length: 199
          repo_is_package: true
