name: Python Observer

on: [push, pull_request]

jobs:
  Python Observer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Python Observer
        uses: lucasvazq/python-observer@master
        with:
          requirements: "pip install -r requirements.txt"
          max_line_length: 199
          repo_is_package: true
