name: Python Observant

on: [push, pull_request]

jobs:
  Python-Observant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Python Observant
        uses: lucasvazq/python-observant@master
        with:
          requirements: "pip install -r requirements.txt"
          max_line_length: 199
          repo_is_package: true
